routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\CategoryController as AdminCategory;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\Admin\ProductController as AdminProduct;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\WishlistController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/logout', [HomeController::class, 'logout'])->name('logout');
Route::get('/my-orders', [OrderController::class, 'showOrders'])->name('orders');

Route::get('category/{id}', [CategoryController::class, 'index'])->name('category');
Route::get('product/{id}', [ProductController::class, 'index'])->name('product');

Route::post('cart/add/{id}', [CartController::class, 'addtocart'])->name('addtocart');
Route::get('cart/show', [CartController::class, 'showCart'])->name('show-cart');
Route::get('cart/clear', [CartController::class, 'clearCart'])->name('clear-cart');
Route::get('cart/remove/{id}', [CartController::class, 'removeProduct'])->name('remove-product');
Route::get('cart/update', [CartController::class, 'update'])->name('update');
Route::get('cart/place-order', [CartController::class, 'placeOrder'])->name('place-order');
Route::post('cart/create-order', [CartController::class, 'addOrder'])->name('add-order');

Route::get('wishlist/add/{id}', [WishlistController::class, 'addToWishlist'])->name('add-wishlist');
Route::get('wishlist/clear', [WishlistController::class, 'clearWishlist'])->name('clear-wishlist');
Route::get('wishlist/show', [WishlistController::class, 'showWishlist'])->name('show-wishlist');
Route::get('wishlist/remove/{id}', [WishlistController::class, 'removeProduct'])->name('remove-in-wishlist');

Route::middleware(['role:admin'])->prefix('admin')->group(function () {
    Route::get('/', [AdminController::class, 'index'])->name('admin');
    Route::get('/logout', [AdminController::class, 'logout'])->name('sign-out');
    Route::resource('/category', AdminCategory::class);
    Route::resource('/brand', BrandController::class);
    Route::resource('/product', AdminProduct::class);
});

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Brand extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'logo',
    ];
}

app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Brand;
use File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Intervention\Image\Facades\Image;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $brands = Brand::get();

        return view('admin.brand.index', compact('brands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|min:2|max:150',
            'logo' => 'required|mimes:jpeg,jpg,png|max:5000'
        ]);
        $brand = new Brand;
        $brand->name = $request->name;

        $image = $request->logo;
        $imageName = date('dmy_H_s_i_').$request->file('logo')->getClientOriginalName();
        $image->move('./images/brands/', $imageName);
        $thumbnail = Image::make('./images/brands/'.$imageName);

        $thumbnail->fit(150, 70);
        $thumbnail->save('./images/brands/thumbnail/'.$imageName);
        $brand->logo = $imageName;

        $brand->save();

        $notification = [
            'message' => 'Бренд успешно добавлен',
            'alert-type' => 'success'
        ];

        return Redirect::back()->with($notification);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function edit(Brand $brand)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|min:2|max:150',
        ]);

        $brand = Brand::find($request->id);
        $brand->name = $request->name;

        $brand->save();

        $notification = [
            'message' => 'Бренд успешно обновлен',
            'alert-type' => 'success'
        ];

        return Redirect::back()->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $brand = Brand::find($id);
        File::delete('./images/brands/thumbnail' .'/'. $brand->logo);
        File::delete('./images/brands' .'/'. $brand->logo);
        $brand->destroy($id);
        $notification = [
            'message' => 'Бренд успешно удален',
            'alert-type' => 'error'
        ];
        return Redirect::back()->with($notification);
    }
}

resources/views/admin/brand/index.blade.php
@extends('layouts.admin_layout')
@section('breadcrumbs')
    <nav class="breadcrumb sl-breadcrumb">
        <a class="breadcrumb-item" href="{{url('admin')}}">Home Admin</a>
        <span class="breadcrumb-item active">Brand</span>
    </nav>
@endsection
@section('title', 'Brands Table')
@section('content')
    <div class="card pd-20 pd-sm-40">
        <h6 class="card-body-title">All Brands
            <a class="btn btn-sm btn-outline-dark" href="#" style="float: right" data-toggle="modal"
               data-target="#modal-create">Add Brand</a>
        </h6>

        <div class="table-wrapper">
            <table id="datatable" class="table display responsive nowrap">
                <thead>
                <tr>
                    <th class="wd-5p">#</th>
                    <th class="wd-15p">Brand name</th>
                    <th class="wd-15p">Brand logo</th>
                    <th class="wd-15p">Created at</th>
                    <th class="wd-10p">Updated At</th>
                    <th class="wd-10p">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($brands as $key => $item)
                    <tr>
                        <td id="id" data-id="{{$item->id}}">{{$key + 1}}</td>
                        <td id="name" data-name="{{$item->name}}">{{$item->name}}</td>
                        <td id="logo"><img src="{{asset('images/brands/thumbnail' .'/'. $item->logo)}}" alt="{{$item->name}}">
                        </td>
                        <td class="">{{\Illuminate\Support\Carbon::parse($item->created_at)->format('d.m.Y')}}</td>
                        <td class="">{{\Illuminate\Support\Carbon::parse($item->updated_at)->format('d.m.Y')}}</td>
                        <td>
                            <div class="btn-group">
                                <button style="float: right" data-toggle="modal"
                                        data-target="#modal-edit" class="btn btn-primary btn-icon mr-2 edit">
                                    <div><i class="fa fa-cog"></i></div>
                                </button>
                                <form action="{{route('brand.destroy', ['brand' => $item->id])}}"
                                      method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger btn-icon"
                                            onclick="return confirm('Удалить бренд?')">
                                        <div><i class="fa fa-trash"></i></div>
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div><!-- table-wrapper -->
    </div><!-- card -->
    <!-- CREATE MODAL -->
    <div id="modal-create" class="modal fade">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content tx-size-sm">
                <div class="modal-header pd-x-20">
                    <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Add new brand</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body pd-40">
                    <form method="post" action="{{route('brand.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="card pd-20 pd-sm-40 form-layout form-layout-4">
                            <div class="row">
                                <label for="name">Название</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror"
                                       placeholder="Enter brand name"
                                       name="name"
                                       id="name">
                                @error('name')
                                <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="row mt-2">
                                <label for="logo">Логотип</label>
                                <input type="file" class="form-control @error('logo') is-invalid @enderror"
                                       name="logo"
                                       id="logo">
                                @error('logo')
                                <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div><!-- row -->
                            <div class="form-layout-footer mg-t-20">
                                <button type="submit" class="btn btn-info mg-r-5">Add brand</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            </div><!-- form-layout-footer -->
                        </div>
                    </form>
                </div><!-- modal-body -->
            </div>
        </div><!-- modal-dialog -->
    </div><!-- modal -->
    @if(!$brands->isEmpty())
        <!-- EDIT MODAL -->
        <div id="modal-edit" class="modal fade">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content tx-size-sm">
                    <div class="modal-header pd-x-20">
                        <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Add new brand</h6>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body pd-40">
                        <form method="post" action="{{route('brand.update', ['brand' => $item->id])}}">
                            @csrf
                            @method('PUT')
                            <div class="card pd-20 pd-sm-40 form-layout form-layout-4">
                                <div class="row">
                                    <label for="name">Название</label>
                                    <input type="text" class="form-control"
                                           placeholder="Enter brand name"
                                           name="name"
                                           id="m_name">
                                </div>
                                <div class="row mt-2">
                                    <label for="logo">Логотип</label>
                                    <input type="file" class="form-control"
                                           name="logo"
                                           id="m_logo">
                                </div>
                                <div class="row mt-2">
                                    <img src="{{asset('images/brands/thumbnail' .'/'. $item->logo)}}" alt="{{$item->name}}">
                                </div>
                                <!-- row -->
                                <input type="hidden" name="id" id="m_id">
                                <div class="row form-layout-footer mg-t-20">
                                    <button type="submit" class="btn btn-info mg-r-5">Submit brand</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                </div><!-- form-layout-footer -->
                            </div>
                        </form>
                    </div><!-- modal-body -->
                </div>
            </div><!-- modal-dialog -->
        </div><!-- modal -->
    @endif
@endsection