routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\CategoryController as AdminCategory;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\Admin\ProductController as AdminProduct;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\WishlistController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/logout', [HomeController::class, 'logout'])->name('logout');
Route::get('/my-orders', [OrderController::class, 'showOrders'])->name('orders');

Route::get('category/{id}', [CategoryController::class, 'index'])->name('category');
Route::get('product/{id}', [ProductController::class, 'index'])->name('product');

Route::post('cart/add/{id}', [CartController::class, 'addtocart'])->name('addtocart');
Route::get('cart/show', [CartController::class, 'showCart'])->name('show-cart');
Route::get('cart/clear', [CartController::class, 'clearCart'])->name('clear-cart');
Route::get('cart/remove/{id}', [CartController::class, 'removeProduct'])->name('remove-product');
Route::get('cart/update', [CartController::class, 'update'])->name('update');
Route::get('cart/place-order', [CartController::class, 'placeOrder'])->name('place-order');
Route::post('cart/create-order', [CartController::class, 'addOrder'])->name('add-order');

Route::get('wishlist/add/{id}', [WishlistController::class, 'addToWishlist'])->name('add-wishlist');
Route::get('wishlist/clear', [WishlistController::class, 'clearWishlist'])->name('clear-wishlist');
Route::get('wishlist/show', [WishlistController::class, 'showWishlist'])->name('show-wishlist');
Route::get('wishlist/remove/{id}', [WishlistController::class, 'removeProduct'])->name('remove-in-wishlist');

Route::middleware(['role:admin'])->prefix('admin')->group(function () {
    Route::get('/', [AdminController::class, 'index'])->name('admin');
    Route::get('/logout', [AdminController::class, 'logout'])->name('sign-out');
    Route::resource('/category', AdminCategory::class);
    Route::resource('/brand', BrandController::class);
    Route::resource('/product', AdminProduct::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'category_id',
        'brand_id',
        'code',
        'quantity',
        'color',
        'size',
        'price',
        'discount_price',
        'video_link',
        'image_one',
        'image_two',
        'image_three',
        'main_slider',
        'mid_slider',
        'hot_deal',
        'hot_new',
        'trend',
        'best_rated',
        'status'
    ];

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    /**
     * @return BelongsTo
     */
    public function brand(): BelongsTo
    {
        return $this->belongsTo(Brand::class, 'brand_id');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use DB;
use File;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Redirect;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $products = Product::get();

        return view('admin.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $categories = Category::get();
        $brands = Brand::get();

        return view('admin.product.create', compact('categories', 'brands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|string|min:3|max:150|unique:products',
            'image_one' => 'mimes:jpeg,jpg,png|max:5000'
        ]);

        $product = new Product;
        $product->title = $request->title;
        $product->description = $request->description;
        $product->category_id = $request->category_id;
        $product->brand_id = $request->brand_id;
        $product->code = $request->code;
        $product->quantity = $request->quantity;
        $product->price = $request->price;
        $product->discount_price = $request->discount_price;

        if ($request->has('image_one')) {
            $image = $request->image_one;
            $imageName = date('dmy_H_s_i_').$request->file('image_one')->getClientOriginalName();
            $image->move('./images/products/', $imageName);
            $thumbnail = Image::make('./images/products/'.$imageName);

            $thumbnail->fit(350, 350);
            $thumbnail->save('./images/products/thumbnail/'.$imageName);
            $product->image_one = $imageName;
        }

        $product->save();

        $notification = [
            'message' => 'Продукт успешно добавлен',
            'alert-type' => 'success'
        ];

        return redirect()->route('product.index')->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function show(int $id)
    {
        $product = Product::find($id);

        return view('admin.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(int $id): RedirectResponse
    {
        $product = Product::find($id);

        File::delete('./images/products/thumbnail/'. $product->image_one);
        File::delete('./images/products/'. $product->image_one);
        $product->destroy($id);

        $notification = [
            'message' => 'Продукт успешно удален',
            'alert-type' => 'error'
        ];
        return Redirect::back()->with($notification);

    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index($id)
    {
        $product = Product::find($id);

        $categories = Category::whereNull('parent_id')->with('children')->orderBy('name')->get();

        $brands = Brand::get();

        return view('product.index', compact('categories', 'brands', 'product'));
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.admin_layout')

@section('breadcrumbs')
    <nav class="breadcrumb sl-breadcrumb">
        <a class="breadcrumb-item" href="{{url('admin')}}">Home Admin</a>
        <span class="breadcrumb-item active">Add Product</span>
    </nav>
@endsection
@section('title', 'Add Product')
@section('content')
    <div class="card pd-20 pd-sm-40">
        <h6 class="card-body-title">
            Add new product
            <a class="btn btn-success btn-sm pull-right" href="{{route('product.index')}}">All products</a>
        </h6>
        <p class="mg-b-20 mg-sm-b-30">Add a new product to the database.</p>
        <form action="{{route('product.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="form-layout">
                <div class="row mg-b-25">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label class="form-control-label">Product title: <span class="tx-danger">*</span></label>
                            <input class="form-control" type="text" name="title" value=""
                                   placeholder="Enter product title">
                        </div>
                    </div><!-- title col-3 -->
                    <div class="col-lg-3">
                        <div class="form-group mg-b-10-force">
                            <label class="form-control-label">Brand: <span class="tx-danger">*</span></label>
                            <select class="form-control select2" name="brand_id">
                                <option selected disabled value="0">Select Brand</option>
                                @foreach($brands as $brand)
                                    <option value="{{$brand->id}}">{{$brand->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><!-- brand col-3 -->
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label class="form-control-label">Product code: <span class="tx-danger">*</span></label>
                            <input class="form-control" type="text" name="code" value=""
                                   placeholder="Enter product code">
                        </div>
                    </div><!-- code col-3 -->
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label class="form-control-label">Product quantity:</label>
                            <input class="form-control" type="text" name="quantity" value=""
                                   placeholder="Enter product quantity">
                        </div>
                    </div><!-- quantity col-3 -->

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label class="form-control-label">Product price:</label>
                            <input class="form-control" type="text" name="price" value=""
                                   placeholder="Enter product price">
                        </div>
                    </div><!-- price col-4 -->
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label class="form-control-label">Sale price:</label>
                            <input class="form-control" type="text" name="discount_price" value=""
                                   placeholder="Enter sale price">
                        </div>
                    </div><!-- sale price col-4 -->
                    <div class="col-lg-4">
                        <div class="form-group mg-b-10-force">
                            <label class="form-control-label">Category: <span class="tx-danger">*</span></label>
                            <select class="form-control select2" name="category_id">
                                <option value="0">Select Category</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><!-- category col-4 -->

                    <div class="col-lg-12">
                        <label class="form-control-label">Description:</label>
                        <textarea rows="8" class="form-control" placeholder="Add description" name="description" id="description"></textarea>
                    </div> <!-- description col-12 -->

                    <div class="col-lg-6 mg-t-20-force mg-lg-t-0">
                        <div class="form-group mg-b-10-force">
                            <label class="form-control-label">Size:</label>
                            <select class="form-control select2" name="size" data-role="tagsinput" multiple>
                            </select>
                        </div>
                    </div><!-- size col-6 -->
                    <div class="col-lg-6 mg-t-20-force mg-lg-t-0">
                        <div class="form-group mg-b-10-force">
                            <label class="form-control-label">Color:</label>
                            <select class="form-control select2" name="color" data-role="tagsinput" multiple>
                            </select>
                        </div>
                    </div><!-- color col-6 -->
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="form-control-label">Video link:</label>
                            <input class="form-control" type="text" name="video_link" value=""
                                   placeholder="Enter video link">
                        </div>
                    </div><!-- video link col-12 -->
                    <div class="col-lg-4 mg-t-20-force mg-lg-t-0">
                        <label class="ckbox">
                            <input type="checkbox" name="main_slider"><span>Main Slider</span>
                        </label>
                        <label class="ckbox">
                            <input type="checkbox" name="mid_slider"><span>Mid Slider</span>
                        </label>
                    </div><!-- sliders col-4 -->
                    <div class="col-lg-4 mg-t-20-force mg-lg-t-0">
                        <label class="ckbox">
                            <input type="checkbox" name="hot_deal"><span>Hot deal</span>
                        </label>
                        <label class="ckbox">
                            <input type="checkbox" name="hot_new"><span>Hot new</span>
                        </label>
                    </div><!-- hot col-4 -->
                    <div class="col-lg-4 mg-t-20-force mg-lg-t-0">
                        <label class="ckbox">
                            <input type="checkbox" name="trand"><span>Trand</span>
                        </label>
                        <label class="ckbox">
                            <input type="checkbox" name="best_rated"><span>Best rated</span>
                        </label>
                    </div><!-- trend & best rated col-4 -->
                    <div class="col-lg-4 mg-t-20-force mg-lg-t-0">
                        <label for="image_one">Image</label>
                        <input type="file" class="form-control @error('image_one') is-invalid @enderror"
                               name="image_one"
                               id="image_one">
                        @error('logo')
                        <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div><!-- file 1 col-4 -->
                </div><!-- row -->

                <div class="form-layout-footer">
                    <button type="submit" class="btn btn-info mg-r-5">Submit Form</button>
                    <button class="btn btn-secondary">Cancel</button>
                </div><!-- form-layout-footer -->
            </div><!-- form-layout -->
        </form>
    </div>
@endsection
@section('scripts')
    <script>
        ClassicEditor
            .create(document.querySelector('#description'))
            .catch(error => {
                console.error(error);
            });
    </script>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.admin_layout')
@section('breadcrumbs')
    <nav class="breadcrumb sl-breadcrumb">
        <a class="breadcrumb-item" href="{{url('admin')}}">Home Admin</a>
        <span class="breadcrumb-item active">Product</span>
    </nav>
@endsection
@section('title', 'Product Table')
@section('content')
    <div class="card pd-20 pd-sm-40">
        <h6 class="card-body-title">All Products
            <a class="btn btn-sm btn-outline-dark" href="{{route('product.create')}}" style="float: right">Add
                Product</a>
        </h6>

        <div class="table-wrapper">
            <table id="datatable" class="table display responsive nowrap">
                <thead>
                <tr>
                    <th class="wd-5p">#</th>
                    <th class="wd-10p">Product title</th>
                    <th class="wd-25p">Description</th>
                    <th class="wd-5p">Code</th>
                    <th class="wd-5p">Brand</th>
                    <th class="wd-5p">Category</th>
                    <th class="wd-5p">Price</th>
                    <th class="wd-5p">Sale price</th>
                    <th class="wd-5p">Quantity</th>
                    <th class="wd-10p">Created at</th>
                    <th class="wd-10p">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($products as $key => $item)
                    <tr>
                        <td>{{$key + 1}}</td>
                        <td>{{$item->title}}</td>
                        <td>{!! $item->description !!}</td>
                        <td>{{$item->code}}</td>
                        <td>{{$item->brand->name}}</td>
                        <td>{{$item->category->name}}</td>
                        <td>{{$item->price}}</td>
                        <td>{{$item->discount_price}}</td>
                        <td>{{$item->quantity}}</td>
                        <td class="">{{\Illuminate\Support\Carbon::parse($item->created_at)->diffForHumans()}}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{route('product.show', ['product' => $item->id])}}" style="float: right"
                                   class="btn btn-primary btn-icon mr-2">
                                    <div><i class="fa fa-eye"></i></div>
                                </a>
                                <form action="{{route('product.destroy', ['product' => $item->id])}}"
                                      method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger btn-icon"
                                            onclick="return confirm('Удалить продукт?')">
                                        <div><i class="fa fa-trash"></i></div>
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div><!-- table-wrapper -->
    </div><!-- card -->
@endsection

resources/views/admin/product/show.blade.php
@extends('layouts.admin_layout')
@section('breadcrumbs')
    <nav class="breadcrumb sl-breadcrumb">
        <a class="breadcrumb-item" href="{{url('admin')}}">Home Admin</a>
        <a class="breadcrumb-item" href="{{url('admin.product.index')}}">All Products</a>
        <a class="breadcrumb-item" href="#">{{$product->category->name}}</a>
        <span class="breadcrumb-item active">{{$product->title}}</span>
    </nav>
@endsection
@section('title', $product->title)
@section('content')
    <div class="card m-2 p-5">
        <div class="card-body-title mg-b-10-force">
            {{$product->title}}
        </div>
        <div class="row">
            <div class="col-6">
                <img src="{{asset('images/products/thumbnail/' . $product->image_one)}}" alt="">
            </div>
            <div class="col-6">
                <div class="mb-2">
                    <div class="text-uppercase text-dark">Brand:</div>
                    {{$product->brand->name}}
                </div>
                <div class="mb-2">
                    <div class="text-uppercase text-dark">Product code:</div>
                    {{$product->code}}
                </div>

                <div class="mb-2">
                    <div class="text-uppercase text-dark">Product quantity:</div>
                    {{$product->quantity}}
                </div>
                <div class="mb-2">
                    <div class="text-uppercase text-dark">Product price:</div>
                    {{$product->price}}
                </div>
                <div class="mb-2">
                    <div class="text-uppercase text-dark">Sale price:</div>
                    {{$product->discount_price}}
                </div>
                <div class="mb-2">
                    <div class="text-uppercase text-dark">Category:</div>
                    {{$product->category->name}}
                </div>
                <div class="mb-2">
                    <div class="text-uppercase text-dark">Description:</div>
                    {!! $product->description !!}
                </div>
            </div>
        </div>
    </div>
@endsection